### ISSUE TITLE
Error: Uncaught [TypeError: src.match is not a function]

### ISSUE THREAD

**Issue by Boscop** [gilbarbara/react-inlinesvg#158]
Thanks for this great package! It works well, but I'm getting the following error when running `yarn test`:
```
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: src.match is not a function]
        at reportException (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
        at invokeEventListeners (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLUnknownElementImpl._dispatch (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLUnknownElementImpl.dispatchEvent (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLUnknownElement.dispatchEvent (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at Object.invokeGuardedCallbackDev (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at commitRoot (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/react-dom/cjs/react-dom.development.js:18948:7)
        at /opt/atlassian/pipelines/agent/build/impero_web/node_modules/react-dom/cjs/react-dom.development.js:20418:5 TypeError: src.match is not a function
        at InlineSVG.<anonymous> (/opt/atlassian/pipelines/agent/build/impero_web/node_modules/react-inlinesvg/src/index.tsx:229:31)
...
```

Any idea why? :)

It's in this line:
https://github.com/gilbarbara/react-inlinesvg/blob/ea11dcbb4ed96fe29d13194d9ef4df0e85ad7729/src/index.tsx#L229

**Comment by Boscop** [comment]
This fixed it:
https://github.com/gilbarbara/react-inlinesvg/issues/140#issuecomment-579063058

**Comment by Guria** [comment]
I am getting the same but in runtime after `react-scripts start`. Started to happen after upgading to reac-scripts@4.0.0
